import '../models/category_model.dart';

final List<CategoryModel> kInitialCategories = [
  CategoryModel(id: 'tech_programming', name: 'Technology & Software', slug: 'tech-software', description: 'Software engineering, cloud architectures, frameworks, and coding.', icon: 'Laptop'),
  CategoryModel(id: 'ai_ml', name: 'Artificial Intelligence & ML', slug: 'ai-ml', description: 'Machine learning models, neural networks, LLMs, and agents.', icon: 'Cpu'),
  CategoryModel(id: 'mobile_dev', name: 'Mobile Development', slug: 'mobile-dev', description: 'Flutter, Android Kotlin, iOS Swift, and cross-platform apps.', icon: 'Smartphone'),
  CategoryModel(id: 'cybersecurity', name: 'Cybersecurity & Privacy', slug: 'cybersecurity', description: 'InfoSec, encryption, threat analysis, penetration testing, and auth.', icon: 'ShieldCheck'),
  CategoryModel(id: 'data_science', name: 'Data Science & Analytics', slug: 'data-science', description: 'Big data, SQL, pipelines, statistics, and business intelligence.', icon: 'Database'),
  CategoryModel(id: 'web3_crypto', name: 'Web3 & Blockchain', slug: 'web3-crypto', description: 'Smart contracts, decentralized systems, cryptography, and protocols.', icon: 'Coins'),
  CategoryModel(id: 'science_physics', name: 'Physics & Astronomy', slug: 'physics-astronomy', description: 'Cosmology, quantum physics, astrophysics, and relativity.', icon: 'Atom'),
  CategoryModel(id: 'mathematics', name: 'Mathematics & Logic', slug: 'mathematics-logic', description: 'Pure math, calculus, discrete math, probability, and proofs.', icon: 'Binary'),
  CategoryModel(id: 'medicine_health', name: 'Medicine & Healthcare', slug: 'medicine-health', description: 'Clinical science, medical research, immunology, and pharmacology.', icon: 'Stethoscope'),
  CategoryModel(id: 'psychology_mind', name: 'Psychology & Neuroscience', slug: 'psychology-mind', description: 'Cognitive science, mental well-being, behavioral studies, and perception.', icon: 'Brain'),
  CategoryModel(id: 'startups_business', name: 'Startups & Venture Capital', slug: 'startups-vc', description: 'Founding companies, fundraising, product-market fit, and scaling.', icon: 'Rocket'),
  CategoryModel(id: 'product_management', name: 'Product Management', slug: 'product-management', description: 'Roadmapping, product discovery, metrics, and user validation.', icon: 'Compass'),
  CategoryModel(id: 'ui_ux_design', name: 'UI/UX & Product Design', slug: 'ui-ux-design', description: 'Interaction design, typography, Figma, and design systems.', icon: 'Palette'),
  CategoryModel(id: 'philosophy', name: 'Philosophy & Ethics', slug: 'philosophy-ethics', description: 'Epistemology, ethics, existentialism, moral philosophy, and logic.', icon: 'BookOpen'),
  CategoryModel(id: 'history_world', name: 'World History', slug: 'world-history', description: 'Ancient civilizations, world wars, archaeology, and historical analysis.', icon: 'Hourglass'),
  CategoryModel(id: 'law_governance', name: 'Law & Governance', slug: 'law-governance', description: 'Constitutional law, international policy, legal rights, and civic systems.', icon: 'Scale'),
  CategoryModel(id: 'economics_finance', name: 'Economics & Markets', slug: 'economics-markets', description: 'Macroeconomics, market mechanisms, interest rates, and monetary policy.', icon: 'TrendingUp'),
  CategoryModel(id: 'investing_wealth', name: 'Personal Finance & Investing', slug: 'investing-wealth', description: 'Asset allocation, retirement planning, index funds, and financial literacy.', icon: 'Briefcase'),
  CategoryModel(id: 'education_pedagogy', name: 'Education & Learning Science', slug: 'education-learning', description: 'Pedagogy, self-directed learning, cognitive retention, and academies.', icon: 'GraduationCap'),
  CategoryModel(id: 'language_linguistics', name: 'Linguistics & Languages', slug: 'linguistics-languages', description: 'Grammar, etymology, language acquisition, and semantics.', icon: 'Languages'),
  CategoryModel(id: 'environmental_science', name: 'Climate & Ecology', slug: 'climate-ecology', description: 'Renewable energy, ecology, climate modeling, and biodiversity.', icon: 'Globe'),
  CategoryModel(id: 'space_exploration', name: 'Space Exploration', slug: 'space-exploration', description: 'Rockets, orbital mechanics, planetary science, and NASA/ESA missions.', icon: 'Compass'),
  CategoryModel(id: 'hardware_iot', name: 'Hardware & Embedded IoT', slug: 'hardware-iot', description: 'Circuits, microcontrollers, Arduino, Raspberry Pi, and robotics.', icon: 'HardDrive'),
  CategoryModel(id: 'automotive_transport', name: 'Electric Vehicles & Mobility', slug: 'ev-mobility', description: 'EVs, battery technology, autonomous driving, and transit.', icon: 'Car'),
  CategoryModel(id: 'creative_writing', name: 'Literature & Writing', slug: 'literature-writing', description: 'Storytelling, narrative arcs, literary analysis, and publishing.', icon: 'PenTool'),
  CategoryModel(id: 'music_audio', name: 'Music Theory & Production', slug: 'music-production', description: 'Composition, synthesizers, acoustic physics, and sound design.', icon: 'Headphones'),
  CategoryModel(id: 'film_cinema', name: 'Film & Cinematography', slug: 'film-cinema', description: 'Directing, screenwriting, cinematography, and film history.', icon: 'Film'),
  CategoryModel(id: 'photography', name: 'Photography & Visual Arts', slug: 'photography', description: 'Optics, exposure, composition, lighting, and camera sensors.', icon: 'Camera'),
  CategoryModel(id: 'fitness_strength', name: 'Fitness & Physical Training', slug: 'fitness-training', description: 'Exercise physiology, strength training, mobility, and athletics.', icon: 'Activity'),
  CategoryModel(id: 'nutrition_diet', name: 'Nutrition & Metabolic Science', slug: 'nutrition-metabolic', description: 'Macronutrients, biochemistry, dietary research, and micronutrients.', icon: 'Utensils'),
  CategoryModel(id: 'gaming_dev', name: 'Game Development & Esports', slug: 'game-dev', description: 'Unreal, Unity, game mechanics, 3D engines, and game balance.', icon: 'Gamepad2'),
  CategoryModel(id: 'architecture_cities', name: 'Architecture & Urban Planning', slug: 'architecture-urban', description: 'Structural engineering, sustainable building, and urban spaces.', icon: 'Building'),
  CategoryModel(id: 'biology_genetics', name: 'Biology & Genetics', slug: 'biology-genetics', description: 'CRISPR, molecular biology, evolutionary theory, and genomics.', icon: 'Dna'),
  CategoryModel(id: 'chemistry', name: 'Chemistry & Materials', slug: 'chemistry-materials', description: 'Organic synthesis, polymers, chemical reactions, and nanotechnology.', icon: 'FlaskConical'),
  CategoryModel(id: 'sociology_culture', name: 'Sociology & Culture', slug: 'sociology-culture', description: 'Demographics, cultural shifts, social dynamics, and community behavior.', icon: 'Users'),
  CategoryModel(id: 'geopolitics', name: 'Geopolitics & Global Affairs', slug: 'geopolitics-affairs', description: 'International diplomacy, alliances, state treaties, and global events.', icon: 'MapPin'),
  CategoryModel(id: 'parenting_family', name: 'Parenting & Child Development', slug: 'parenting-family', description: 'Child psychology, family structures, early education, and guidance.', icon: 'Baby'),
  CategoryModel(id: 'cooking_gastronomy', name: 'Culinary Arts & Gastronomy', slug: 'culinary-arts', description: 'Food science, culinary techniques, fermentation, and recipes.', icon: 'ChefHat'),
  CategoryModel(id: 'travel_cultures', name: 'Global Travel & Exploration', slug: 'travel-exploration', description: 'Geography, cultural travel, expedition prep, and regional customs.', icon: 'Plane'),
  CategoryModel(id: 'gardening_agriculture', name: 'Gardening & Agriculture', slug: 'gardening-agriculture', description: 'Soil science, horticulture, permaculture, and crop cultivation.', icon: 'Sprout'),
  CategoryModel(id: 'pets_veterinary', name: 'Veterinary Science & Animals', slug: 'veterinary-animals', description: 'Animal physiology, pet care, behavior, and zoology.', icon: 'Dog'),
  CategoryModel(id: 'real_estate', name: 'Real Estate & Property', slug: 'real-estate', description: 'Commercial leases, homeownership, appraisal, and land rights.', icon: 'Home'),
  CategoryModel(id: 'productivity_habits', name: 'Productivity & Deep Work', slug: 'productivity-habits', description: 'Time management, systems thinking, focus, and cognitive stamina.', icon: 'CheckCircle'),
  CategoryModel(id: 'leadership_management', name: 'Leadership & Team Dynamics', slug: 'leadership-management', description: 'Organizational psychology, management, negotiation, and strategy.', icon: 'Award'),
  CategoryModel(id: 'marketing_growth', name: 'Marketing & Brand Strategy', slug: 'marketing-growth', description: 'Demand generation, copywriting, consumer psychology, and SEO.', icon: 'Megaphone'),
  CategoryModel(id: 'devops_infra', name: 'DevOps & Cloud Infrastructure', slug: 'devops-infra', description: 'Kubernetes, Terraform, CI/CD pipelines, reliability, and SRE.', icon: 'Server'),
  CategoryModel(id: 'journalism_media', name: 'Media & Independent Journalism', slug: 'media-journalism', description: 'Fact-checking, investigative journalism, digital media ethics.', icon: 'Newspaper'),
  CategoryModel(id: 'diy_crafts', name: 'Craftsmanship & Woodworking', slug: 'craftsmanship-diy', description: 'Joinery, metalworking, fabrication, electronics repair, and tools.', icon: 'Wrench'),
  CategoryModel(id: 'astrology_mythology', name: 'Mythology & Folklore', slug: 'mythology-folklore', description: 'Comparative mythology, pantheons, folklore, and cultural legends.', icon: 'Moon'),
  CategoryModel(id: 'open_discussion', name: 'Open Community Inquiries', slug: 'open-inquiries', description: 'General questions, thought experiments, cross-disciplinary debates.', icon: 'HelpCircle'),
];
